export const exportData = [
    {  id: 5,
      ordinalNo: 105,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 4,
      ordinalNo: 104,
      title: 'devlopment history',
      type: 'building',
  
    },
    {  id: 1,
      ordinalNo: 101,
      title: 'devlopment history',
      type: 'building',
  
    },
    {  id: 2,
      ordinalNo: 102,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 3,
      ordinalNo: 103,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 6,
      ordinalNo: 106,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 7,
      ordinalNo: 107,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 9,
      ordinalNo: 108,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 3,
      ordinalNo: 109,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 10,
      ordinalNo: 110,
      title: 'devlopment history',
      type: 'building',
    },
  
    {  id: 11,
      ordinalNo: 111,
      title: 'devlopment history',
      type: 'building',
    },
    {  id: 12,
      ordinalNo: 112,
      title: 'devlopment history',
      type: 'building',
    },
  ]

